### PR TITLE
add new test

### PR DESCRIPTION
**Pull request by k-raczkowska**
Zostawiam komentarz

---
This change is [Reviewable](https://reviewable.io/reviews/k-raczkowska/rmeter/1)

### CODE REVIEW

**Comment by k-raczkowska** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

_[tests/testthat/test_add.r, line 3 at r1](https://reviewable.io:443/reviews/k-raczkowska/rmeter/1#-KVRxRNQ97hfRsrGul5T:-KVRxRNQ97hfRsrGul5U:bb7p34n) ([raw file](https://github.com/k-raczkowska/rmeter/blob/ad848f191e11fd2773007dd42a5217e70f864dfa/tests/testthat/test_add.r#L3)):_

> ``` Rebol
> context('addition tests')
> 
> test_that('1 + 1 = 2', {
> ```

test

---

_[tests/testthat/test_add.r, line 4 at r1](https://reviewable.io:443/reviews/k-raczkowska/rmeter/1#-KVRxGsPGwPG3hWoaZUf:-KVRxGsQYK6nIdgX4qUP:b-eo2hpv) ([raw file](https://github.com/k-raczkowska/rmeter/blob/ad848f191e11fd2773007dd42a5217e70f864dfa/tests/testthat/test_add.r#L4)):_

> ``` Rebol
> 
> test_that('1 + 1 = 2', {
>   expect_equal(2, addition(1,1))
> ```

To działa

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/k-raczkowska/rmeter/1)_

**Comment by k-raczkowska** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

_[tests/testthat/test_add.r, line 1 at r1](https://reviewable.io:443/reviews/k-raczkowska/rmeter/1#-KVYtKcGYepYXy7Qao-l:-KVYtKcGYepYXy7Qao-m:bkm0r17) ([raw file](https://github.com/k-raczkowska/rmeter/blob/418acb777580af7700a1287e6825a0a21cfea8d2/tests/testthat/test_add.r#L1)):_

> ``` Rebol
> context('addition tests')
> ```

trzeci komentarz

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/k-raczkowska/rmeter/1)_

**Comment by buksior** [comment]
Drugi komentarz

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/k-raczkowska/rmeter/1#-:-KV_bEt2Mg-KPAdPwqUy:b-oqcyap)_

**Comment by k-raczkowska** [comment]
Trzeci komentarz

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/k-raczkowska/rmeter/1#-:-KV_fiSlB6ZOW0zOQPcr:b6o95a3)_

**Comment by k-raczkowska** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[tests/testthat/test_add.r, line 1 at r1](https://reviewable.io:443/reviews/k-raczkowska/rmeter/1#-KVYtKcGYepYXy7Qao-l:-KV_foOqUvigUlhuYS1l:b-896fix) ([raw file](https://github.com/k-raczkowska/rmeter/blob/418acb777580af7700a1287e6825a0a21cfea8d2/tests/testthat/test_add.r#L1)):_
<details><summary>

<i>Previously, k-raczkowska wrote…</i></summary>



> trzeci komentarz
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/k-raczkowska/rmeter/1)_

**Comment by buksior** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[tests/testthat/test_add.r, line 3 at r1](https://reviewable.io:443/reviews/k-raczkowska/rmeter/1#-KVRxRNQ97hfRsrGul5T:-KVa2hrW8nTkY0-tmC2B:byl06mf) ([raw file](https://github.com/k-raczkowska/rmeter/blob/ad848f191e11fd2773007dd42a5217e70f864dfa/tests/testthat/test_add.r#L3)):_
<details><summary>

<i>Previously, k-raczkowska wrote…</i></summary>



> test
> </details>
> Do poprawienia

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/k-raczkowska/rmeter/1)_

**Comment by k-raczkowska** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[tests/testthat/test_add.r, line 3 at r1](https://reviewable.io:443/reviews/k-raczkowska/rmeter/1#-KVRxRNQ97hfRsrGul5T:-KVa2wAf-s0JksgcRk3h:b-8abwxk) ([raw file](https://github.com/k-raczkowska/rmeter/blob/ad848f191e11fd2773007dd42a5217e70f864dfa/tests/testthat/test_add.r#L3)):_
<details><summary>

<i>Previously, buksior wrote…</i></summary>



> Do poprawienia
> </details>
> Block

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/k-raczkowska/rmeter/1)_

**Comment by buksior** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[tests/testthat/test_add.r, line 3 at r1](https://reviewable.io:443/reviews/k-raczkowska/rmeter/1#-KVRxRNQ97hfRsrGul5T:-KVa2n3W0IMQ2-GE18yh:b2ni9ah) ([raw file](https://github.com/k-raczkowska/rmeter/blob/ad848f191e11fd2773007dd42a5217e70f864dfa/tests/testthat/test_add.r#L3)):_
<details><summary>

<i>Previously, k-raczkowska wrote…</i></summary>



> Block
> </details>
> ok

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/k-raczkowska/rmeter/1)_

**Pull request merged**
